
import { motion } from "framer-motion";
import { Users, Award, TrendingUp } from "lucide-react";

const stats = [
  {
    icon: Users,
    value: "50,000+",
    label: "Active Creators",
    description: "Joined our thriving community"
  },
  {
    icon: TrendingUp,
    value: "$2M+",
    label: "Monthly Earnings",
    description: "Generated by our creators"
  },
  {
    icon: Award,
    value: "95%",
    label: "Success Rate",
    description: "For dedicated creators"
  }
];

export const CommunityHighlights = () => {
  return (
    <section className="py-20 relative overflow-hidden">
      <div className="container mx-auto px-4">
        <div className="grid md:grid-cols-3 gap-8">
          {stats.map((stat, index) => (
            <motion.div
              key={stat.label}
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.5, delay: index * 0.2 }}
              className="p-6 rounded-2xl bg-luxury-dark/50 border border-luxury-primary/20 backdrop-blur-lg"
            >
              <div className="flex flex-col items-center text-center">
                <stat.icon className="w-12 h-12 text-luxury-primary mb-4" />
                <motion.h3 
                  className="text-4xl font-bold mb-2"
                  initial={{ scale: 0.5 }}
                  whileInView={{ scale: 1 }}
                  transition={{ duration: 0.5, delay: index * 0.2 + 0.3 }}
                >
                  {stat.value}
                </motion.h3>
                <p className="text-xl font-semibold mb-2">{stat.label}</p>
                <p className="text-luxury-neutral">{stat.description}</p>
              </div>
            </motion.div>
          ))}
        </div>
      </div>
    </section>
  );
};
